package com.Wsdl2Code.WebServices.MAService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/15/2016 6:42:16 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Department implements KvmSerializable {
    
    public int depId;
    public String departmentName;
    public String logo;
    
    public Department(){}
    
    public Department(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("depId"))
        {
            Object obj = soapObject.getProperty("depId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                depId = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                depId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("DepartmentName"))
        {
            Object obj = soapObject.getProperty("DepartmentName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                departmentName = j.toString();
            }else if (obj!= null && obj instanceof String){
                departmentName = (String) obj;
            }
        }
        if (soapObject.hasProperty("Logo"))
        {
            Object obj = soapObject.getProperty("Logo");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                logo = j.toString();
            }else if (obj!= null && obj instanceof String){
                logo = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return depId;
            case 1:
                return departmentName;
            case 2:
                return logo;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 3;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "depId";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DepartmentName";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Logo";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
