package com.Wsdl2Code.WebServices.MAService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/15/2016 6:42:16 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.MAService.VectorString;
import com.Wsdl2Code.WebServices.MAService.VectorDocument;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Library implements KvmSerializable {
    
    public VectorString departments;
    public VectorDocument documents;
    public int documentCount;
    public int pageCount;
    
    public Library(){}
    
    public Library(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("Departments"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Departments");
            departments = new VectorString(j);
        }
        if (soapObject.hasProperty("Documents"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("Documents");
            documents = new VectorDocument(j);
        }
        if (soapObject.hasProperty("DocumentCount"))
        {
            Object obj = soapObject.getProperty("DocumentCount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                documentCount = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                documentCount = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("PageCount"))
        {
            Object obj = soapObject.getProperty("PageCount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pageCount = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                pageCount = (Integer) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return departments;
            case 1:
                return documents;
            case 2:
                return documentCount;
            case 3:
                return pageCount;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "Departments";
                break;
            case 1:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "Documents";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "DocumentCount";
                break;
            case 3:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "PageCount";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
