package com.Wsdl2Code.WebServices.MAService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/15/2016 6:42:16 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Status implements KvmSerializable {
    
    public String statusCode;
    public String description;
    public String messageTR;
    public String messageEN;
    
    public Status(){}
    
    public Status(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("StatusCode"))
        {
            Object obj = soapObject.getProperty("StatusCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                statusCode = j.toString();
            }else if (obj!= null && obj instanceof String){
                statusCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("Description"))
        {
            Object obj = soapObject.getProperty("Description");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                description = j.toString();
            }else if (obj!= null && obj instanceof String){
                description = (String) obj;
            }
        }
        if (soapObject.hasProperty("MessageTR"))
        {
            Object obj = soapObject.getProperty("MessageTR");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                messageTR = j.toString();
            }else if (obj!= null && obj instanceof String){
                messageTR = (String) obj;
            }
        }
        if (soapObject.hasProperty("MessageEN"))
        {
            Object obj = soapObject.getProperty("MessageEN");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                messageEN = j.toString();
            }else if (obj!= null && obj instanceof String){
                messageEN = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return statusCode;
            case 1:
                return description;
            case 2:
                return messageTR;
            case 3:
                return messageEN;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "StatusCode";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Description";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "MessageTR";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "MessageEN";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
